SayMeCoco/DiceStarter

README.md
client/src/App.test.tsx
client/src/App.tsx
client/src/components/home/home.tsx
client/src/index.tsx

Feature/home half finished 

---

client/src/components/searchBar/searchBar.tsx
client/src/index.css

componente creado y prueba de pull request

added seaarch bar component

---

client/src/components/landing/landing.tsx

Initial Landing commit

---

client/src/App.tsx

Añadi "/" a las rutas. Me olvide antes. Grax.

Add landing route

---

client/src/components/searchBar/searchBar.css
client/src/components/searchBar/searchBar.tsx

estilos añadidos y modificaciones menores

basic styles added to the search bar and minor modifications

---

client/.gitignore
client/package.json
client/src/components/landing/assets/table.svg
client/src/components/landing/landing.css
client/src/components/landing/landing.tsx

La landing con el boton andando y un poco de estilo.

Landing with working button towards HOME

---

client/src/components/home/home.tsx
client/src/components/productCard/productCard.css
client/src/components/productCard/productCard.tsx
client/src/components/productCards/productCards.css
client/src/components/productCards/productCards.tsx

We created the Cards and the Card, we made a display of unreal information, and gave styles

Cards and Card added

---

client/src/app/types/types.ts
client/src/components/formCreateProduct/formCreateProduct.tsx
client/src/types.ts

quite la carpeta types para añadir mis types al otro documento creado.

modified types document

---

client/src/App.tsx
client/src/app/reducers/formSlice.ts
client/src/components/formCreateProduct/formCreateProduct.tsx
client/src/types.ts

comenzado el control de formulario y coneccion con redux

start controled formulary and coneccion with redux

---

client/src/components/formCreateProduct/formCreateProduct.tsx

añadido los controles y verificaciones del formulario para posterior conexión con redux y las bases de datos en algunos aspectos funcionales.

completed controled formulary

---

api/package.json
api/routes/products.js
client/src/app/reducers/handleProductsSlice.ts
client/src/components/productCard/productCard.tsx
client/src/components/productCards/productCards.tsx
client/src/components/productDetail/productDetail.tsx
client/src/components/searchBar/searchBar.tsx
client/src/types.ts

Gets all products from back-end

---

client/src/app/reducers/handleProductsSlice.ts
client/src/components/home/home.tsx
client/src/components/productDetail/productDetail.tsx
client/src/types.ts

connects productDetail component front-to-back

connects productDetail front-toback

---

client/src/app/reducers/handleProductsSlice.ts
client/src/types.ts

Action to get Categories, action to edit product in DB. Some types also.

Categories GET, Product PUT

---

client/src/components/formRegisterUser/formRegisterForm.tsx
client/src/types.ts

formulario re registro (continuar despues)

iniciado formulario de registro

---

client/src/app/reducers/handleProductsSlice.ts
client/src/components/formCreateProduct/formCreateProduct.tsx
client/src/types.ts

form hotfix

---

api/routes/products.js
client/src/app/reducers/handleProductsSlice.ts
client/src/components/home/home.tsx
client/src/components/productCards/productCards.tsx
client/src/types.ts

Succesfully filters products by category

adds filters for products

---

client/src/app/reducers/handleProductsSlice.ts
client/src/components/formCreateProduct/formCreateProduct.tsx
client/src/components/home/home.tsx
client/src/components/productSelects/productSelects.tsx
client/src/types.ts

now we can sort products by A-Z, Z-A, Maximum Price, Minimum Price, Maximum Rating and Minimum Rating

adds sort Select to productSelects

---

client/src/app/reducers/handleProductsSlice.ts
client/src/components/productSelects/productSelects.tsx

Hotfix for Selects

---

client/src/app/reducers/formSlice.ts
client/src/components/formCreateProduct/formCreateProduct.tsx
client/src/components/productList/productList.tsx
client/src/components/productsList/productsList.tsx
client/src/types.ts

Fixed products list. Added non working select.

Fixed products list

---

client/src/components/productsList/productsList.tsx

Pagination of Products List

---

client/src/app/reducers/handleProductsSlice.ts
client/src/components/productList/productList.tsx

Now everything works in the Products List.

Categories fixed in Products List

---

client/src/App.tsx
client/src/components/productsList/productsList.css
client/src/components/productsList/productsList.tsx
client/src/components/searchBar/searchBar.tsx

Products list finished

---

client/src/components/formRegisterUser/formRegisterForm.tsx

añadido las expresiones regulares en el formulario de creacion

added regular expresions for controling user formulary

---

client/src/app/reducers/registerReducer.ts
client/src/components/countrySelect/countrySelect.tsx
client/src/components/formRegisterUser/formRegisterForm.tsx
client/src/types.ts

el formulario funciona, se renderiza en la ruta /register

Register form can creater new users and its completed controlated

---

api/models/Product.js
api/models/Reviews.js
client/package.json
client/src/components/formCreateProduct/formCreateProduct.tsx
client/src/components/productDetail/productDetail.tsx
client/src/types.ts

Images host added so we can have images for products and admin can upload them

HostImages

---

client/src/components/cart/cart.tsx
client/src/components/cartProduct/cartProduct.tsx
client/src/components/cartTotal/cartTotal.tsx

changes made to cart so there are no longer multiple equal products and amount changes to display the total

changes made to cart, no more double products

---

client/src/components/cart/cart.tsx

Sintaxis errors on findDuplicates function that was pushing undefined instead of product

sintaxis errors

---

api/middleware/auth.js
client/src/app/actions/cartActions/index.ts
client/src/components/cartProduct/cartProduct.tsx

autorization solucionada al borrar

---

client/package.json
client/src/components/productsList/productsList.tsx
client/src/components/userReview/userReview.css
client/src/components/userReview/userReview.tsx
client/tsconfig.json

eslint version fix and parser fix

eslint fix and parser fix
